import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { App } from "components/app";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main_image_container">
          <Image
            className="main_image"
            src="/me.jpg"
            width={60}
            height={60}
            alt="self image"
          />
        </div>
        <App />
      </main>
    </div>
  );
};

export default Home;
